//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kotor_Randomizer_2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool module_rando_active {
            get {
                return ((bool)(this["module_rando_active"]));
            }
            set {
                this["module_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sound_rando_active {
            get {
                return ((bool)(this["sound_rando_active"]));
            }
            set {
                this["sound_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MixNpcAndPartySounds {
            get {
                return ((bool)(this["MixNpcAndPartySounds"]));
            }
            set {
                this["MixNpcAndPartySounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeAreaMusic {
            get {
                return ((int)(this["RandomizeAreaMusic"]));
            }
            set {
                this["RandomizeAreaMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeAmbientNoise {
            get {
                return ((int)(this["RandomizeAmbientNoise"]));
            }
            set {
                this["RandomizeAmbientNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeCutsceneNoise {
            get {
                return ((int)(this["RandomizeCutsceneNoise"]));
            }
            set {
                this["RandomizeCutsceneNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeNpcSounds {
            get {
                return ((int)(this["RandomizeNpcSounds"]));
            }
            set {
                this["RandomizeNpcSounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePartySounds {
            get {
                return ((int)(this["RandomizePartySounds"]));
            }
            set {
                this["RandomizePartySounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeBattleMusic {
            get {
                return ((int)(this["RandomizeBattleMusic"]));
            }
            set {
                this["RandomizeBattleMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModulesInitialized {
            get {
                return ((bool)(this["ModulesInitialized"]));
            }
            set {
                this["ModulesInitialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModulePresetSelected {
            get {
                return ((bool)(this["ModulePresetSelected"]));
            }
            set {
                this["ModulePresetSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastPresetComboIndex {
            get {
                return ((int)(this["LastPresetComboIndex"]));
            }
            set {
                this["LastPresetComboIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kotor1Path {
            get {
                return ((string)(this["Kotor1Path"]));
            }
            set {
                this["Kotor1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MilestoneDelete {
            get {
                return ((bool)(this["MilestoneDelete"]));
            }
            set {
                this["MilestoneDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeMG {
            get {
                return ((bool)(this["IncludeMG"]));
            }
            set {
                this["IncludeMG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeAll {
            get {
                return ((bool)(this["IncludeAll"]));
            }
            set {
                this["IncludeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool model_rando_active {
            get {
                return ((bool)(this["model_rando_active"]));
            }
            set {
                this["model_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool item_rando_active {
            get {
                return ((bool)(this["item_rando_active"]));
            }
            set {
                this["item_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Seed {
            get {
                return ((int)(this["Seed"]));
            }
            set {
                this["Seed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeedSelected {
            get {
                return ((bool)(this["SeedSelected"]));
            }
            set {
                this["SeedSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool texture_rando_active {
            get {
                return ((bool)(this["texture_rando_active"]));
            }
            set {
                this["texture_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twoda_rando_active {
            get {
                return ((bool)(this["twoda_rando_active"]));
            }
            set {
                this["twoda_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool text_rando_active {
            get {
                return ((bool)(this["text_rando_active"]));
            }
            set {
                this["text_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool other_rando_active {
            get {
                return ((bool)(this["other_rando_active"]));
            }
            set {
                this["other_rando_active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeArmor {
            get {
                return ((int)(this["RandomizeArmor"]));
            }
            set {
                this["RandomizeArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeStims {
            get {
                return ((int)(this["RandomizeStims"]));
            }
            set {
                this["RandomizeStims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeBelts {
            get {
                return ((int)(this["RandomizeBelts"]));
            }
            set {
                this["RandomizeBelts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeVarious {
            get {
                return ((int)(this["RandomizeVarious"]));
            }
            set {
                this["RandomizeVarious"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeHides {
            get {
                return ((int)(this["RandomizeHides"]));
            }
            set {
                this["RandomizeHides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeArmbands {
            get {
                return ((int)(this["RandomizeArmbands"]));
            }
            set {
                this["RandomizeArmbands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeDroid {
            get {
                return ((int)(this["RandomizeDroid"]));
            }
            set {
                this["RandomizeDroid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeGloves {
            get {
                return ((int)(this["RandomizeGloves"]));
            }
            set {
                this["RandomizeGloves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeImplants {
            get {
                return ((int)(this["RandomizeImplants"]));
            }
            set {
                this["RandomizeImplants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMask {
            get {
                return ((int)(this["RandomizeMask"]));
            }
            set {
                this["RandomizeMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePaz {
            get {
                return ((int)(this["RandomizePaz"]));
            }
            set {
                this["RandomizePaz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMines {
            get {
                return ((int)(this["RandomizeMines"]));
            }
            set {
                this["RandomizeMines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeUpgrade {
            get {
                return ((int)(this["RandomizeUpgrade"]));
            }
            set {
                this["RandomizeUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeBlasters {
            get {
                return ((int)(this["RandomizeBlasters"]));
            }
            set {
                this["RandomizeBlasters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeCreature {
            get {
                return ((int)(this["RandomizeCreature"]));
            }
            set {
                this["RandomizeCreature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeLightsabers {
            get {
                return ((int)(this["RandomizeLightsabers"]));
            }
            set {
                this["RandomizeLightsabers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeGrenades {
            get {
                return ((int)(this["RandomizeGrenades"]));
            }
            set {
                this["RandomizeGrenades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMelee {
            get {
                return ((int)(this["RandomizeMelee"]));
            }
            set {
                this["RandomizeMelee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeDoorModels {
            get {
                return ((int)(this["RandomizeDoorModels"]));
            }
            set {
                this["RandomizeDoorModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeCharModels {
            get {
                return ((int)(this["RandomizeCharModels"]));
            }
            set {
                this["RandomizeCharModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePlaceModels {
            get {
                return ((int)(this["RandomizePlaceModels"]));
            }
            set {
                this["RandomizePlaceModels"] = value;
            }
        }
    }
}
