//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kotor_Randomizer_2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Module {
            get {
                return ((bool)(this["DoRandomization_Module"]));
            }
            set {
                this["DoRandomization_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Sound {
            get {
                return ((bool)(this["DoRandomization_Sound"]));
            }
            set {
                this["DoRandomization_Sound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MixNpcAndPartySounds {
            get {
                return ((bool)(this["MixNpcAndPartySounds"]));
            }
            set {
                this["MixNpcAndPartySounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeAreaMusic {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeAreaMusic"]));
            }
            set {
                this["RandomizeAreaMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeAmbientNoise {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeAmbientNoise"]));
            }
            set {
                this["RandomizeAmbientNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeCutsceneNoise {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeCutsceneNoise"]));
            }
            set {
                this["RandomizeCutsceneNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeNpcSounds {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeNpcSounds"]));
            }
            set {
                this["RandomizeNpcSounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizePartySounds {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizePartySounds"]));
            }
            set {
                this["RandomizePartySounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeBattleMusic {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeBattleMusic"]));
            }
            set {
                this["RandomizeBattleMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModulesInitialized {
            get {
                return ((bool)(this["ModulesInitialized"]));
            }
            set {
                this["ModulesInitialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModulePresetSelected {
            get {
                return ((bool)(this["ModulePresetSelected"]));
            }
            set {
                this["ModulePresetSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastPresetComboIndex {
            get {
                return ((int)(this["LastPresetComboIndex"]));
            }
            set {
                this["LastPresetComboIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kotor1Path {
            get {
                return ((string)(this["Kotor1Path"]));
            }
            set {
                this["Kotor1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Model {
            get {
                return ((bool)(this["DoRandomization_Model"]));
            }
            set {
                this["DoRandomization_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Item {
            get {
                return ((bool)(this["DoRandomization_Item"]));
            }
            set {
                this["DoRandomization_Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Seed {
            get {
                return ((int)(this["Seed"]));
            }
            set {
                this["Seed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Texture {
            get {
                return ((bool)(this["DoRandomization_Texture"]));
            }
            set {
                this["DoRandomization_Texture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_TwoDA {
            get {
                return ((bool)(this["DoRandomization_TwoDA"]));
            }
            set {
                this["DoRandomization_TwoDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Text {
            get {
                return ((bool)(this["DoRandomization_Text"]));
            }
            set {
                this["DoRandomization_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRandomization_Other {
            get {
                return ((bool)(this["DoRandomization_Other"]));
            }
            set {
                this["DoRandomization_Other"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeArmor {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeArmor"]));
            }
            set {
                this["RandomizeArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeStims {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeStims"]));
            }
            set {
                this["RandomizeStims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeBelts {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeBelts"]));
            }
            set {
                this["RandomizeBelts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeVarious {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeVarious"]));
            }
            set {
                this["RandomizeVarious"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeHides {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeHides"]));
            }
            set {
                this["RandomizeHides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeArmbands {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeArmbands"]));
            }
            set {
                this["RandomizeArmbands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeDroid {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeDroid"]));
            }
            set {
                this["RandomizeDroid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeGloves {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeGloves"]));
            }
            set {
                this["RandomizeGloves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeImplants {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeImplants"]));
            }
            set {
                this["RandomizeImplants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeMask {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeMask"]));
            }
            set {
                this["RandomizeMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizePaz {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizePaz"]));
            }
            set {
                this["RandomizePaz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeMines {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeMines"]));
            }
            set {
                this["RandomizeMines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeUpgrade {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeUpgrade"]));
            }
            set {
                this["RandomizeUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeBlasters {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeBlasters"]));
            }
            set {
                this["RandomizeBlasters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeCreature {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeCreature"]));
            }
            set {
                this["RandomizeCreature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeLightsabers {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeLightsabers"]));
            }
            set {
                this["RandomizeLightsabers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeGrenades {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeGrenades"]));
            }
            set {
                this["RandomizeGrenades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel RandomizeMelee {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["RandomizeMelee"]));
            }
            set {
                this["RandomizeMelee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeDoorModels {
            get {
                return ((int)(this["RandomizeDoorModels"]));
            }
            set {
                this["RandomizeDoorModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeCharModels {
            get {
                return ((int)(this["RandomizeCharModels"]));
            }
            set {
                this["RandomizeCharModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePlaceModels {
            get {
                return ((int)(this["RandomizePlaceModels"]));
            }
            set {
                this["RandomizePlaceModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeCubeMaps {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeCubeMaps"]));
            }
            set {
                this["TextureRandomizeCubeMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeCreatures {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeCreatures"]));
            }
            set {
                this["TextureRandomizeCreatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeEffects {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeEffects"]));
            }
            set {
                this["TextureRandomizeEffects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeItems {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeItems"]));
            }
            set {
                this["TextureRandomizeItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizePlanetary {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizePlanetary"]));
            }
            set {
                this["TextureRandomizePlanetary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeNPC {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeNPC"]));
            }
            set {
                this["TextureRandomizeNPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizePlayHeads {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizePlayHeads"]));
            }
            set {
                this["TextureRandomizePlayHeads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizePlayBodies {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizePlayBodies"]));
            }
            set {
                this["TextureRandomizePlayBodies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizePlaceables {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizePlaceables"]));
            }
            set {
                this["TextureRandomizePlaceables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeParty {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeParty"]));
            }
            set {
                this["TextureRandomizeParty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeStunt {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeStunt"]));
            }
            set {
                this["TextureRandomizeStunt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeVehicles {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeVehicles"]));
            }
            set {
                this["TextureRandomizeVehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeWeapons {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeWeapons"]));
            }
            set {
                this["TextureRandomizeWeapons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::kotor_Randomizer_2.RandomizationLevel TextureRandomizeOther {
            get {
                return ((global::kotor_Randomizer_2.RandomizationLevel)(this["TextureRandomizeOther"]));
            }
            set {
                this["TextureRandomizeOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KotorIsRandomized {
            get {
                return ((bool)(this["KotorIsRandomized"]));
            }
            set {
                this["KotorIsRandomized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection FirstnamesM {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FirstnamesM"]));
            }
            set {
                this["FirstnamesM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection FirstnamesF {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FirstnamesF"]));
            }
            set {
                this["FirstnamesF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection Lastnames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Lastnames"]));
            }
            set {
                this["Lastnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PolymorphMode {
            get {
                return ((bool)(this["PolymorphMode"]));
            }
            set {
                this["PolymorphMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizeNameGen {
            get {
                return ((bool)(this["RandomizeNameGen"]));
            }
            set {
                this["RandomizeNameGen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighQuality")]
        public global::kotor_Randomizer_2.TexturePack TexturePack {
            get {
                return ((global::kotor_Randomizer_2.TexturePack)(this["TexturePack"]));
            }
            set {
                this["TexturePack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizePazaakDecks {
            get {
                return ((bool)(this["RandomizePazaakDecks"]));
            }
            set {
                this["RandomizePazaakDecks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection PresetPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PresetPaths"]));
            }
            set {
                this["PresetPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::kotor_Randomizer_2.ModuleExtras ModuleExtrasValue {
            get {
                return ((global::kotor_Randomizer_2.ModuleExtras)(this["ModuleExtrasValue"]));
            }
            set {
                this["ModuleExtrasValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::kotor_Randomizer_2.TextSettings TextSettingsValue {
            get {
                return ((global::kotor_Randomizer_2.TextSettings)(this["TextSettingsValue"]));
            }
            set {
                this["TextSettingsValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizePartyMembers {
            get {
                return ((bool)(this["RandomizePartyMembers"]));
            }
            set {
                this["RandomizePartyMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerifyReachability {
            get {
                return ((bool)(this["VerifyReachability"]));
            }
            set {
                this["VerifyReachability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoalIsMalak {
            get {
                return ((bool)(this["GoalIsMalak"]));
            }
            set {
                this["GoalIsMalak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoalIsPazaak {
            get {
                return ((bool)(this["GoalIsPazaak"]));
            }
            set {
                this["GoalIsPazaak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoalIsStarMaps {
            get {
                return ((bool)(this["GoalIsStarMaps"]));
            }
            set {
                this["GoalIsStarMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowGlitchClip {
            get {
                return ((bool)(this["AllowGlitchClip"]));
            }
            set {
                this["AllowGlitchClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowGlitchDlz {
            get {
                return ((bool)(this["AllowGlitchDlz"]));
            }
            set {
                this["AllowGlitchDlz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowGlitchFlu {
            get {
                return ((bool)(this["AllowGlitchFlu"]));
            }
            set {
                this["AllowGlitchFlu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowGlitchGpw {
            get {
                return ((bool)(this["AllowGlitchGpw"]));
            }
            set {
                this["AllowGlitchGpw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreOnceEdges {
            get {
                return ((bool)(this["IgnoreOnceEdges"]));
            }
            set {
                this["IgnoreOnceEdges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRandoRules {
            get {
                return ((bool)(this["UseRandoRules"]));
            }
            set {
                this["UseRandoRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizeSwoopBoosters {
            get {
                return ((bool)(this["RandomizeSwoopBoosters"]));
            }
            set {
                this["RandomizeSwoopBoosters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomizeSwoopObstacles {
            get {
                return ((bool)(this["RandomizeSwoopObstacles"]));
            }
            set {
                this["RandomizeSwoopObstacles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveDmcaMusic {
            get {
                return ((bool)(this["RemoveDmcaMusic"]));
            }
            set {
                this["RemoveDmcaMusic"] = value;
            }
        }
    }
}
